// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: byteservice.proto

package byteservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос содержит поле типа bytes
type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_byteservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_byteservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_byteservice_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Ответ возвращает обработанные байты и их размер
type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_byteservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_byteservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_byteservice_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProcessResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_byteservice_proto protoreflect.FileDescriptor

const file_byteservice_proto_rawDesc = "" +
	"\n" +
	"\x11byteservice.proto\x12\vbyteservice\"*\n" +
	"\x0eProcessRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"=\n" +
	"\x0fProcessResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size2Z\n" +
	"\rByteProcessor\x12I\n" +
	"\fProcessBytes\x12\x1b.byteservice.ProcessRequest\x1a\x1c.byteservice.ProcessResponseB\x0fZ\r./byteserviceb\x06proto3"

var (
	file_byteservice_proto_rawDescOnce sync.Once
	file_byteservice_proto_rawDescData []byte
)

func file_byteservice_proto_rawDescGZIP() []byte {
	file_byteservice_proto_rawDescOnce.Do(func() {
		file_byteservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_byteservice_proto_rawDesc), len(file_byteservice_proto_rawDesc)))
	})
	return file_byteservice_proto_rawDescData
}

var file_byteservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_byteservice_proto_goTypes = []any{
	(*ProcessRequest)(nil),  // 0: byteservice.ProcessRequest
	(*ProcessResponse)(nil), // 1: byteservice.ProcessResponse
}
var file_byteservice_proto_depIdxs = []int32{
	0, // 0: byteservice.ByteProcessor.ProcessBytes:input_type -> byteservice.ProcessRequest
	1, // 1: byteservice.ByteProcessor.ProcessBytes:output_type -> byteservice.ProcessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_byteservice_proto_init() }
func file_byteservice_proto_init() {
	if File_byteservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_byteservice_proto_rawDesc), len(file_byteservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_byteservice_proto_goTypes,
		DependencyIndexes: file_byteservice_proto_depIdxs,
		MessageInfos:      file_byteservice_proto_msgTypes,
	}.Build()
	File_byteservice_proto = out.File
	file_byteservice_proto_goTypes = nil
	file_byteservice_proto_depIdxs = nil
}
