// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc1
// source: byteservice.proto

package byteservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ByteProcessor_ProcessBytes_FullMethodName = "/byteservice.ByteProcessor/ProcessBytes"
)

// ByteProcessorClient is the client API for ByteProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Описание сервиса
type ByteProcessorClient interface {
	ProcessBytes(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
}

type byteProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewByteProcessorClient(cc grpc.ClientConnInterface) ByteProcessorClient {
	return &byteProcessorClient{cc}
}

func (c *byteProcessorClient) ProcessBytes(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, ByteProcessor_ProcessBytes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ByteProcessorServer is the server API for ByteProcessor service.
// All implementations must embed UnimplementedByteProcessorServer
// for forward compatibility.
//
// Описание сервиса
type ByteProcessorServer interface {
	ProcessBytes(context.Context, *ProcessRequest) (*ProcessResponse, error)
	mustEmbedUnimplementedByteProcessorServer()
}

// UnimplementedByteProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedByteProcessorServer struct{}

func (UnimplementedByteProcessorServer) ProcessBytes(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessBytes not implemented")
}
func (UnimplementedByteProcessorServer) mustEmbedUnimplementedByteProcessorServer() {}
func (UnimplementedByteProcessorServer) testEmbeddedByValue()                       {}

// UnsafeByteProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ByteProcessorServer will
// result in compilation errors.
type UnsafeByteProcessorServer interface {
	mustEmbedUnimplementedByteProcessorServer()
}

func RegisterByteProcessorServer(s grpc.ServiceRegistrar, srv ByteProcessorServer) {
	// If the following call panics, it indicates UnimplementedByteProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ByteProcessor_ServiceDesc, srv)
}

func _ByteProcessor_ProcessBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ByteProcessorServer).ProcessBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ByteProcessor_ProcessBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ByteProcessorServer).ProcessBytes(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ByteProcessor_ServiceDesc is the grpc.ServiceDesc for ByteProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ByteProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "byteservice.ByteProcessor",
	HandlerType: (*ByteProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessBytes",
			Handler:    _ByteProcessor_ProcessBytes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "byteservice.proto",
}
